### PR TITLE
Allow sending of null values in response for DN case data

### PR DESCRIPTION
**Pull request by tchow8**
[DIV-4321 - CCD - Stale data in CCD](https://tools.hmcts.net/jira/browse/DIV-4321)

For PR https://github.com/hmcts/div-decree-nisi-frontend/pull/294

### CODE REVIEW

**Comment by hosainnet** [comment]
Does this require testing or can we merge?

**Comment by tchow8** [comment]
Can merge. If you want to be safe, a QA could test.

**Comment by hosainnet** [comment]
Can merge?

**Comment by tchow8** [comment]
Yes, whenever @hmcts/divorce-qa is ready :)

**Comment by hosainnet** [comment]
@vianvi  @nsingamsetty ?

**Pull request merged**
