### PR TITLE
Changing DivorceCostOptionsDN to dynamic list

### PR DESCRIPTION
**Pull request by mounikahmcts**
https://tools.hmcts.net/jira/browse/DIV-4727
Dependent on https://github.com/hmcts/div-case-orchestration-service/pull/316

### CODE REVIEW

**Comment by hosainnet** [comment]
@mounikahmcts conflict here FYI

**Comment by mounikahmcts** [comment]
> @mounikahmcts conflict here FYI

Will close this PR as we are still waiting for CCD to come back

**Comment by hosainnet** [comment]
@mounikahmcts is that the same for https://github.com/hmcts/div-case-orchestration-service/pull/316 ?

**Comment by mounikahmcts** [comment]
> @mounikahmcts is that the same for [hmcts/div-case-orchestration-service#316](https://github.com/hmcts/div-case-orchestration-service/pull/316) ?

Yes

**Pull request closed without merging**
