### PR TITLE
[PREVIEW] DIV-5766 Map DN Clarification from Session to CCD

### PR DESCRIPTION
**Pull request by tchow8**
# Description

[DIV-5766](https://tools.hmcts.net/jira/browse/DIV-5766)

Note this PR does not map back from CCD to Dn Clarification, because every frontend clarification journey does not rely on the previous journey(s).

This PR maps two DN Clarification fields from frontend format to CCD format. The mapper always appends incoming data to the existing collection and never removes old data, as the user can have multiple clarification journeys which are always in addition of the previous clarification journey.

This PR also does not overwrite existing documents in D8DocumentsGenerated when the document type is defined as other (it continue to overwrite non-generic documents).

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

* Hardware:
* O/S and version:
* JDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by hosainnet** [comment]
Can this wait for https://github.com/hmcts/div-common-lib/pull/9 by any chance?

**Comment by tchow8** [comment]
@hosainnet Depends when it'll be ready? It blocks complete testing of DN Clarification Journey.

**Comment by hosainnet** [comment]
@tchow8 technically that PR is ready - @yarpo what do you think?

**Comment by tchow8** [comment]
It'd be good if that can be done soon. This PR is having the dependency check issues which is fixed in COS, and also some Jenkinsfile deprecation issues.

**Comment by yarpo** [comment]
@tchow8, @hosainnet - we can merge it, if it's ready. I will take care of moving it into lib.

**Comment by tchow8** [comment]
Just updating all the outdated Jenkinsfile, Dockerfile and Charts to try and get a green build.

**Comment by tchow8** [comment]
Closing in preference to:
https://github.com/hmcts/div-common-lib/pull/12

**Comment by tchow8** [comment]
Keeping branch until other PR is approved and merged.

**Comment by tchow8** [comment]
Reopening as we may require this first instead of CFS

**Comment by tchow8** [comment]
Refactoring

**Pull request closed without merging**
